# Generated by Django 6.1.1 on 2026-09-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('destacado', models.CharField(max_length=200)),
                ('nivel_demanda', models.CharField(max_length=50)),
            ],
        ),
    ]
