# Generated by Django 6.1.1 on 2026-09-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='zonas.zona')),
            ],
        ),
    ]
